### PR TITLE
Add 'end of book' bookmark to end of list

### LINKED ISSUE #146: Move 'go to start of book' and 'go to end of book' into the bookmarks menu
Issue: It is very easy to accidentally press 'go to start/end of book whilst reading, which then loses the reader their place. This has been demonstrated in user trials.

Therefore remove them from the main navigation menu. 

In the bookmarks sub menu add two 'pseudo-bookmarks', i.e. not deletable or defined by the user, labelled "start of book" and "end of book" (whereas other bookmarks are labelled with text from the page, these have fixed labels). 

The former to always be the first bookmark (even if the user defines a bookmark at the first page); the latter to always be the last bookmark in the list, no matter how many user defined bookmarks are added.

### PR DESCRIPTION
**Pull request by Lazarus404**
"End of book" link now added to bookmarks even if it's not a bookmark. Fixes #146.

### CODE REVIEW

**Comment by kasbah** [comment]
Can you address my comment please? Why is this needed? What's the test case to reproduce this issue?

> Regarding ecd45f4, can you explain what's going on here? Seems like a hack rather than a solution. I was never able to reproduce the issue this is supposed to solve.

**Comment by Lazarus404** [comment]
The ticket asks that End of Book be added as the last bookmark to “always” be there. Currently, on Master, the End of Book bookmark is only visible if the last page is bookmarked. This commit satisfies the ticket requirement

**Comment by kasbah** [comment]
I think you misunderstood the way this works since #150. We add permanent end-of-book and start-of-book bookmarks to the bookmarks state. These bookmarks are always there and cannot be deleted.

I couldn't reproduce the issue reported. Were you able to?

**Comment by Lazarus404** [comment]
Yes, there is no End of Book bookmark... will read over #150

**Comment by Lazarus404** [comment]
So, I still see this.  Why would it work differently for me than you?

**Comment by kasbah** [comment]
Are you sure the book has more than one page? Seems like we need to try it out in person otherwise.

**Comment by kasbah** [comment]
Yeah, there are parts of the code that remove duplicate bookmarks so they would have to be re-done if we want a start and end bookmark pointing to the same place. This way was just a bit easier.

**Pull request closed without merging**
